### PR TITLE
invalidate_zone_for_many_files option in cloudflare class should default to true (fixes #10)

### LINKED ISSUE #10: Invalidation threshold not respected
As of #9, there's a `invalidate_zone_for_many_files` option for Cloudflare that means "if I have more than 50 files to invalidate, I'll just invalidate the zone (to avoid hitting the API rate limit)." The option is supposed to default to true, but wouldn't work until [I added it explicitly](https://github.com/ashfurrow/blog/commit/97002273338b25e4eff5a4dea4b557e5bd34f982).

Failing deploy: https://travis-ci.org/ashfurrow/blog/builds/119957771#L7481
Succeeding deploy (with explicit option): https://travis-ci.org/ashfurrow/blog/builds/120216017#L5992

Please let me know if I can be off assistance debugging.

### PR DESCRIPTION
**Pull request by manuelmeurer**

### CODE REVIEW

File: spec/lib/middleman-cdn/cdns/cloudflare_spec.rb [hunk 1]
```diff
@@ -114,6 +114,14 @@
...
         end
 
+        context "invalidate_zone_for_many_files is not set" do
+          before do
+            expect(options.has_key?(:invalidate_zone_for_many_files)).to be_falsy
+          end
+
+          it_behaves_like "invalidating the entire zone"
+        end
+
```
Comment (leighmcculloch) [inline spec/lib/middleman-cdn/cdns/cloudflare_spec.rb]: Nice! Thanks for adding this spec.

File: lib/middleman-cdn/cdns/cloudflare.rb [hunk 2]
```diff
@@ -23,6 +23,7 @@ def self.example_configuration_elements
       end
 
       def invalidate(options, files, all: false)
+        options[:invalidate_zone_for_many_files] = true unless options.has_key?(:invalidate_zone_for_many_files)
```
Comment (leighmcculloch) [inline lib/middleman-cdn/cdns/cloudflare.rb]: `has_key?` => `key?`. re: http://batsov.com/articles/2013/08/21/the-elements-of-style-in-ruby-number-9-hash-number-has-key-and-hash-number-has-value-are-deprecated/

**Comment by leighmcculloch** [comment]
Thanks for fixing this so quickly! One comment, otherwise lgtm. If you can fix that I'll merge it.

File: lib/middleman-cdn/cdns/cloudflare.rb (hunk 2 above)
Comment (manuelmeurer) [inline lib/middleman-cdn/cdns/cloudflare.rb]: Good catch! I actually googled `has_key?` before adding it here but couldn't find any indication that it's deprecated: http://ruby-doc.org/core-2.3.0/Hash.html#method-i-has_key-3F
Still, if Matz says so. :smile: I'll replace it.

Comment (leighmcculloch) [inline lib/middleman-cdn/cdns/cloudflare.rb]: Yeah it's not deprecated in the true sense of the word, I think it's just not favoured because the preferred way of naming methods in ruby has been agreed to leave out `is` and `has` as function prefixes.

**Comment by leighmcculloch** [comment]
Released in version `0.1.16`.
